server:
  port: 8080

spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: password

logging:
  level:
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG