package com.bs.myneighbourhood.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "NEIGHBOUR-HOOD")
public class SocietyDocument {
    private String id;
    private String type;
    private String name;
    private String contactNumber;
    private String contactPerson;
    private String address;
    private String city;
    private String pinCode;


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    @DynamoDBRangeKey
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }




    @DynamoDBAttribute
    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    @DynamoDBAttribute
    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    @DynamoDBAttribute
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @DynamoDBAttribute
    public String getPinCode() {
        return pinCode;
    }

    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }
}